# Deploy epics-dev container to DLS argus cluster GPFS node for
# kafka performance testing

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: controls-kafka
  name: data
  labels:
    app: epics-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: controls-kafka
  name: epics-dev
  labels:
    app: epics-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: epics-dev
  template:
    metadata:
      labels:
        app: epics-dev
    spec:
      terminationGracePeriodSeconds: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
        - name: gpfs
          hostPath:
            # The gpfs perf test mount writeable by
            path: /mnt/gpfs03/performance_testing
        - name: home
          hostPath:
            path: /home
        - name: work
          hostPath:
            path: /dls_sw/work
        - name: prod
          hostPath:
            path: /dls_sw/prod
        - name: etc
          hostPath:
            path: /dls_sw/etc
        - name: apps
          hostPath:
            path: /dls_sw/apps
        - name: epics
          hostPath:
            path: /dls_sw/epics
      containers:
        - name: epics-dev
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 37631
            runAsGroup: 37798
          image: gcr.io/diamond-pubreg/controls/dev-kafka:latest
          command: ["/bin/sh"]
          args: ["-c", "while true; do sleep 10; done"]
          volumeMounts:
            - name: data
              mountPath: /data
            - name: gpfs
              mountPath: /gpfs
            - name: home
              mountPath: /home
            - name: work
              mountPath: /dls_sw/work
            - name: prod
              mountPath: /dls_sw/prod
            - name: etc
              mountPath: /dls_sw/etc
            - name: apps
              mountPath: /dls_sw/apps
            - name: epics
              mountPath: /dls_sw/epics
          resources:
            limits:
              memory: "2048Mi"
              cpu: "4"
            requests:
              memory: "512Mi"
              cpu: "1"
          imagePullPolicy: Always
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - cs05r-sc-cloud-17.diamond.ac.uk
